/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;

import entities.OngTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author WEBSTER
 */
public class TelaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdministrador
     */
    public TelaAdministrador() {
        super("Tela do Administrador");
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        admTable = new javax.swing.JTable();
        admMenuBar = new javax.swing.JMenuBar();
        admMenu = new javax.swing.JMenu();
        removerAdmMenuItem = new javax.swing.JMenuItem();
        cadAdmMenuItem = new javax.swing.JMenuItem();
        ongsMenu = new javax.swing.JMenu();
        addOngMenuItem = new javax.swing.JMenuItem();
        editarOngMenuItem = new javax.swing.JMenuItem();
        removeOngMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1327, 773));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ongs"));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 582));

        admTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(admTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        admMenu.setText("Administradores");

        removerAdmMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_delete.png"))); // NOI18N
        removerAdmMenuItem.setText("Remover Administrador");
        removerAdmMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerAdmMenuItemActionPerformed(evt);
            }
        });
        admMenu.add(removerAdmMenuItem);

        cadAdmMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_add.png"))); // NOI18N
        cadAdmMenuItem.setText("Adicionar Administrador");
        cadAdmMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadAdmMenuItemActionPerformed(evt);
            }
        });
        admMenu.add(cadAdmMenuItem);

        admMenuBar.add(admMenu);

        ongsMenu.setText("ONGs");

        addOngMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group_add.png"))); // NOI18N
        addOngMenuItem.setText("Adicionar nova ONG");
        addOngMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOngMenuItemActionPerformed(evt);
            }
        });
        ongsMenu.add(addOngMenuItem);

        editarOngMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group_edit.png"))); // NOI18N
        editarOngMenuItem.setText("Editar ONG");
        editarOngMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarOngMenuItemActionPerformed(evt);
            }
        });
        ongsMenu.add(editarOngMenuItem);

        removeOngMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group_delete.png"))); // NOI18N
        removeOngMenuItem.setText("Remover ONG");
        ongsMenu.add(removeOngMenuItem);

        admMenuBar.add(ongsMenu);

        setJMenuBar(admMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1265, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(18, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(50, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(51, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removerAdmMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerAdmMenuItemActionPerformed
        TelaRemoveAdm admDelet = new TelaRemoveAdm();
        admDelet.setVisible(true);
    }//GEN-LAST:event_removerAdmMenuItemActionPerformed

    private void editarOngMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarOngMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarOngMenuItemActionPerformed

    private void cadAdmMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadAdmMenuItemActionPerformed
        TelaAddAdm admAdd = new TelaAddAdm();
        admAdd.setVisible(true);
    }//GEN-LAST:event_cadAdmMenuItemActionPerformed

    private void addOngMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOngMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addOngMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdministrador().setVisible(true);
            }
        });
    }
    
    
    
    public void carregarTabela(){
        try {
           this.admTable.setModel(new OngTableModel());
           this.admTable.getColumnModel().getColumn(0).setPreferredWidth(1);
           this.admTable.getColumnModel().getColumn(1).setPreferredWidth(150);
           this.admTable.getColumnModel().getColumn(2).setPreferredWidth(150);
           this.admTable.getColumnModel().getColumn(3).setPreferredWidth(70);
           this.admTable.getColumnModel().getColumn(4).setPreferredWidth(1);
           this.admTable.getColumnModel().getColumn(5).setPreferredWidth(70);
           this.admTable.getColumnModel().getColumn(6).setPreferredWidth(200);
           this.admTable.getColumnModel().getColumn(7).setPreferredWidth(90);
           this.admTable.getColumnModel().getColumn(8).setPreferredWidth(100);
           
        }
        catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Falha ao buscar as ONGs cadastradas.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addOngMenuItem;
    private javax.swing.JMenu admMenu;
    private javax.swing.JMenuBar admMenuBar;
    private javax.swing.JTable admTable;
    private javax.swing.JMenuItem cadAdmMenuItem;
    private javax.swing.JMenuItem editarOngMenuItem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu ongsMenu;
    private javax.swing.JMenuItem removeOngMenuItem;
    private javax.swing.JMenuItem removerAdmMenuItem;
    // End of variables declaration//GEN-END:variables
}
