
package application;

import DAO.LocalidadesDAO;
import DAO.OngDAO;
import entities.Cidades;
import entities.Ong;
import entities.UFs;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;


public class TelaEditOng extends javax.swing.JFrame {

    public TelaEditOng() {
        super("Edição de ONGs");
        initComponents();
        this.setLocationRelativeTo(null);
        ativarOngCbx();
        ativarCidadeInicialmente();
        ativarUfsInicialmente();
        TextFildInicial();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atualizarButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ongsComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        telefoneTextField = new javax.swing.JTextField();
        nomeTextField = new javax.swing.JTextField();
        cnpjTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        causaTextField = new javax.swing.JTextField();
        siteTextField = new javax.swing.JTextField();
        cidadesComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ufsComboBox = new javax.swing.JComboBox<>();
        voltarButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        descricaoButton = new javax.swing.JButton();
        atualizarButton1 = new javax.swing.JButton();

        atualizarButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        atualizarButton.setText("ATUALIZAR");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ongsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ongsComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Selecione a ONG que será editada");

        jLabel2.setText("Nome");

        jLabel3.setText("Email");

        jLabel4.setText("Telefone");

        jLabel5.setText("Causa");

        jLabel6.setText("CNPJ");

        jLabel7.setText("Site");

        cidadesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadesComboBoxActionPerformed(evt);
            }
        });

        jLabel8.setText("Cidade");

        jLabel9.setText("UF");

        ufsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ufsComboBoxActionPerformed(evt);
            }
        });

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("ID");

        descricaoButton.setText("Atualizar Descrição da ONG");
        descricaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricaoButtonActionPerformed(evt);
            }
        });

        atualizarButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        atualizarButton1.setText("ATUALIZAR");
        atualizarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cnpjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(causaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(telefoneTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(siteTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descricaoButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ufsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(cidadesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltarButton)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37))
                    .addComponent(ongsComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(atualizarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(voltarButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ongsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descricaoButton))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(telefoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(causaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cnpjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(siteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cidadesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(ufsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(atualizarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void ongsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ongsComboBoxActionPerformed
        TextFildInicial();
    }//GEN-LAST:event_ongsComboBoxActionPerformed

    private void cidadesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadesComboBoxActionPerformed

    }//GEN-LAST:event_cidadesComboBoxActionPerformed

    private void descricaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricaoButtonActionPerformed
        TelaDescricao td = new TelaDescricao();
        td.setVisible(true);
    }//GEN-LAST:event_descricaoButtonActionPerformed

    private void ufsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ufsComboBoxActionPerformed
        cidadesComboBox.removeAllItems();
        ativarCbxCidade();
    }//GEN-LAST:event_ufsComboBoxActionPerformed

    private void atualizarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarButton1ActionPerformed
         try{
            attOng();
            JOptionPane.showMessageDialog(null, "ONG atualizada com sucesso.");
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null, "Falha ao atualizar ONG.\n" + e);
        }
    }//GEN-LAST:event_atualizarButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditOng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditOng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditOng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditOng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEditOng().setVisible(true);
            }
        });
    }
    
    
    public void ativarCidadeInicialmente(){
        try{
            LocalidadesDAO dao = new LocalidadesDAO();
            for(Cidades cd : dao.buscarCidades()){
               cidadesComboBox.addItem(cd);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Falha ao buscar as cidades cadastradas.\n" + e);
            
        }
    }
     
     
    public void ativarUfsInicialmente(){
        try{
            LocalidadesDAO dao = new LocalidadesDAO();
            for(UFs uf : dao.buscarUfs()){
               ufsComboBox.addItem(uf);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Falha ao buscar as Unidade Federativa cadastradas.");
        }
    }
    
     public void ativarCbxCidade(){
        try{
            LocalidadesDAO dao = new LocalidadesDAO();
            UFs ufcbx = (UFs) ufsComboBox.getSelectedItem();
            for(Cidades cd : dao.buscaPorUf(ufcbx)){
               cidadesComboBox.addItem(cd);
               
               
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Falha ao buscar as cidades cadastradas.");
        }
    }
    
     
    public void ativarOngCbx(){
        try{
            OngDAO dao = new OngDAO();
            for(Ong ong : dao.buscarOngs()){
                ongsComboBox.addItem(ong);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Falha ao buscar as ONGs");
        }
    }
  
    
    public void TextFildInicial(){
        Ong ong = (Ong) ongsComboBox.getSelectedItem();
        idTextField.setText(String.valueOf(ong.getId()));
        idTextField.setEditable(false);
        nomeTextField.setText(ong.getNome());
        emailTextField.setText(ong.getEmail());
        telefoneTextField.setText(ong.getTelefone());
        causaTextField.setText(ong.getCausa());
        cnpjTextField.setText(ong.getCnpj());
        siteTextField.setText(ong.getSite());
        
        //cidadesComboBox.setSelectedIndex(3);
        //ufsComboBox.setSelectedIndex(5);
    }
    
    public void attOng()throws Exception{
        
        String id = idTextField.getText();
        String nome = nomeTextField.getText();
        String email = emailTextField.getText();
        String telefone = telefoneTextField.getText();
        String causa = causaTextField.getText();
        String cnpj = cnpjTextField.getText();
        String site = siteTextField.getText();
        Object cidade = cidadesComboBox.getSelectedItem();
        Object uf = ufsComboBox.getSelectedItem();
        
        Ong ong = new Ong();
        
        ong.setId(Integer.parseInt(id));
        ong.setNome(nome);
        ong.setEmail(email);
        ong.setTelefone(telefone);
        ong.setCausa(causa);
        ong.setCnpj(cnpj);
        ong.setSite(site);
        ong.setCidade(String.valueOf(cidade));
        ong.setUf(String.valueOf(uf));
        
        OngDAO dao = new OngDAO();
        dao.attOngs(ong);
    }
    
    //Tentativa de setar valor inicial as cbx
    /*public void percorrerCbx() {
        Ong ong = new Ong();
        // Obtém a Cidade e a UF da ONG que está sendo editada (substitua os valores pelas suas variáveis)
        String cidadeOng = ong.getCidade(); // Substitua "getCidade()" pelo método real que retorna a Cidade no seu objeto ONG
        String ufOng = ong.getUf(); // Substitua "getUF()" pelo método real que retorna a UF no seu objeto ONG

        // Percorre os itens da comboBox para encontrar o índice correspondente à Cidade e UF
        for (int i = 0; i < cidadesComboBox.getItemCount(); i++) {
            Object item = cidadesComboBox.getItemAt(i);

            // Verifica se o item é do tipo ONG
            if (item instanceof Object) {
                Object ongItem = (Object) item; // Conversão explícita para o tipo ONG

                String cidade = ongItem.getCidade(); // Substitua "getCidade()" pelo método real que retorna a Cidade no seu objeto ONG
                String uf = ongItem.getUF(); // Substitua "getUF()" pelo método real que retorna a UF no seu objeto ONG

                // Verifica se a Cidade e UF correspondem aos da ONG
                if (cidade.equals(cidadeOng) && uf.equals(ufOng)) {
                    cidadesComboBox.setSelectedIndex(i); // Define o índice encontrado como selecionado
                    break; // Encerra o loop após encontrar o índice correto
                }
            }
        }

    }*/
     
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarButton;
    private javax.swing.JButton atualizarButton1;
    private javax.swing.JTextField causaTextField;
    private javax.swing.JComboBox<Object> cidadesComboBox;
    private javax.swing.JTextField cnpjTextField;
    private javax.swing.JButton descricaoButton;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JComboBox<Object> ongsComboBox;
    private javax.swing.JTextField siteTextField;
    private javax.swing.JTextField telefoneTextField;
    private javax.swing.JComboBox<Object> ufsComboBox;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
